config_dir: ~/.config/bash

# bash_bin: "/usr/local/bin/bash" # the dir might be old homebrew download path
bash_bin: "/opt/homebrew/bin/bash"
tmp_dir: "/tmp/bash/"
version: 5.0
patch_versions:
  - "001"
  - "002"
  - "003"
  - "004"
  - "005"
  - "006"
  - "007"
  - "008"
  - "009"
  - "010"
  - "011"
  - "012"
  - "013"
  - "014"
  - "015"
  - "016"
  - "017"
  - "018"
