# https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_cask_module.html
- name: Install Homebrew Cask Packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: Install SauceCodePro Nerd Font Complete via brew --cask
  community.general.homebrew_cask:
    name: font-sauce-code-pro-nerd-font
    state: present
    install_options: "appdir=~/Library/Fonts"