- name: Debug
  debug:
    msg: "{{ ansible_facts.distribution }}"

# https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_tap_module.html
- name: Homebrew tap
  community.general.homebrew_tap:
    name: homebrew/homebrew-core
    state: "present"
  with_items: "{{ brew_taps }}"

# https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Install Homebrew Packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: "present"